# Generated by Django 4.1.1 on 2022-10-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='numberplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberPlate', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=10)),
                ('picture', models.CharField(max_length=20)),
                ('auth', models.IntegerField(max_length=2)),
                ('dateAndTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
