# Generated by Django 4.1.3 on 2022-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npDetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplate',
            name='auth',
            field=models.IntegerField(),
        ),
    ]
