# Generated by Django 4.1.1 on 2022-11-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npDetection', '0002_alter_numberplate_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
