# Generated by Django 4.1.1 on 2022-11-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npDetection', '0003_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
