# Generated by Django 4.1.1 on 2022-12-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npDetection', '0006_normaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='numPlateRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberPlate', models.CharField(max_length=20)),
                ('auth', models.IntegerField()),
                ('dateAndTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='numberplate',
            name='dateAndTime',
        ),
    ]
