# Generated by Django 4.1.1 on 2022-12-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npDetection', '0007_numplaterecords_remove_numberplate_dateandtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberplate',
            name='picture',
        ),
    ]
