# Generated by Django 4.1.1 on 2022-12-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npDetection', '0008_remove_numberplate_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberplate',
            old_name='numberPlate',
            new_name='numPlate',
        ),
        migrations.RenameField(
            model_name='numplaterecords',
            old_name='numberPlate',
            new_name='numPlate',
        ),
    ]
